config/routes.rb
Rails.application.routes.draw do
  resources :locales
  resources :tags
  resources :posts
  resources :community_users
  resources :communities
  resources :topics

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }
  root :to => 'posts#index'
  get 'about' => 'pages#about'
  get 'basic' => 'pages#basic'
  get 'posts/:tid/:pid' => 'posts#view'

end

app/helpers/community_topics_helper.rb
module CommunityTopicsHelper
end

app/views/community_topics/_form.html.erb
<%= form_for(@community_topic) do |f| %>
  <% if @community_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@community_topic.errors.count, "error") %> prohibited this community_topic from being saved:</h2>

      <ul>
      <% @community_topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :community_id %><br />
	<%= collection_select(:community_topic, :community_id, current_user.own_communities , :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br />
	<%= collection_select(:community_topic, :topic_id, Topic.all, :id, :subject) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/community_topics/edit.html.erb
<h1>Editing community_topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @community_topic %> |
<%= link_to 'Back', community_topics_path %>

app/views/community_topics/index.html.erb
<h1>Listing community_topics</h1>

<table>
  <tr>
    <th>Community</th>
    <th>Topic</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @community_topics.each do |community_topic| %>
  <tr>
    <td><%= community_topic.community_id %></td>
    <td><%= community_topic.topic_id %></td>
    <td><%= community_topic.status %></td>
    <td><%= link_to 'Show', community_topic %></td>
    <td><%= link_to 'Edit', edit_community_topic_path(community_topic) %></td>
    <td><%= link_to 'Destroy', community_topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Community topic', new_community_topic_path %>

app/views/community_topics/new.html.erb
<h1>New community_topic</h1>

<%= render 'form' %>

<%= link_to 'Back', community_topics_path %>

app/views/community_topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Community:</b>
  <%= @community_topic.community_id %>
</p>

<p>
  <b>Topic:</b>
  <%= @community_topic.topic_id %>
</p>

<p>
  <b>Status:</b>
  <%= @community_topic.status %>
</p>


<%= link_to 'Edit', edit_community_topic_path(@community_topic) %> |
<%= link_to 'Back', community_topics_path %>