config/routes.rb
Rails.application.routes.draw do
  resources :locales
  resources :tags
  resources :posts
  resources :community_users
  resources :communities
  resources :topics

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }
  root :to => 'posts#index'
  get 'about' => 'pages#about'
  get 'basic' => 'pages#basic'
  get 'posts/:tid/:pid' => 'posts#view'

end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/controllers/post_tags_controller.rb
class PostTagsController < ApplicationController
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/views/post_tags/_form.html.erb
<%= form_for(@post_tag) do |f| %>
  <% if @post_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_tag.errors.count, "error") %> prohibited this post_tag from being saved:</h2>

      <ul>
      <% @post_tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br />
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br />
    <%= f.number_field :tag_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_tags/edit.html.erb
<h1>Editing post_tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_tag %> |
<%= link_to 'Back', post_tags_path %>

app/views/post_tags/index.html.erb
<h1>Listing post_tags</h1>

<table>
  <tr>
    <th>Post</th>
    <th>Tag</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_tags.each do |post_tag| %>
  <tr>
    <td><%= post_tag.post_id %></td>
    <td><%= post_tag.tag_id %></td>
    <td><%= link_to 'Show', post_tag %></td>
    <td><%= link_to 'Edit', edit_post_tag_path(post_tag) %></td>
    <td><%= link_to 'Destroy', post_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post tag', new_post_tag_path %>

app/views/post_tags/new.html.erb
<h1>New post_tag</h1>

<%= render 'form' %>

<%= link_to 'Back', post_tags_path %>

app/views/post_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Post:</b>
  <%= @post_tag.post_id %>
</p>

<p>
  <b>Tag:</b>
  <%= @post_tag.tag_id %>
</p>


<%= link_to 'Edit', edit_post_tag_path(@post_tag) %> |
<%= link_to 'Back', post_tags_path %>