config/routes.rb
Rails.application.routes.draw do
  resources :locales
  resources :tags
  resources :posts
  resources :community_users
  resources :communities
  resources :topics

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords     => "users/passwords",
    :omniauth_callbacks => "users/omniauth_callbacks" 
  }
  root :to => 'posts#index'
  get 'about' => 'pages#about'
  get 'basic' => 'pages#basic'
  get 'posts/:tid/:pid' => 'posts#view'

end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43979218-2', 'ancient-falls-3709.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_joined_communities.html.erb
<header><h1><%= t 'community.joined'%></h1></header>
<ul>
<% Community.find(CommunityUser.communities(current_user.id)).each do |community| %>
  <li><img class="icon" width="30" height="30" src="<%= s3 community.photo.url(:small) %>"><%= link_to community.name, community %></li>
<% end %>
</ul>

app/views/layouts/_links.html.erb
<header><h1><%= t 'links'%></h1></header>
<ul>
  <li><%= image_tag("home.png" , class:"icon")%><%= link_to t('home')        , :posts %></li>
  <li><%= image_tag("human.png", class:"icon")%><%= link_to t('edit_profile'), edit_user_registration_path %></li>
  <li><%= image_tag("make.png" , class:"icon")%><%= link_to t('community.new')   , new_community_path %></li>
  <li><%= image_tag("post.png" , class:"icon")%><%= link_to t('post.list')   , posts_path  %></li>
  <li><%= image_tag("community.png", class:"icon")%><%= link_to t('community.list')  , communities_path %></li>
  <li><%= image_tag("topic.png", class:"icon")%><%= link_to t('topic.list')  , topics_path %></li>
</ul>

app/views/layouts/_navbar.html.erb
<section id="menu_section">
  <span id="menu"><%= image_tag("menu.png", class:"menuicon")%></span>
</section>
<section id="login_info" class="navbar-text pull-right">
  <%= link_to t("home"), :posts %> | 
  <strong><%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %></strong> | 
  <%= link_to t("logout"), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
</section>

app/views/layouts/_search_post.html.erb
<%= form_tag posts_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search], {'x-webkit-speech'=>'','x-webkit-grammar' => 'builtin:search'} %>
  <select id="submit_path">
    <option value="1"><%= t 'post.name'%></option>
    <option value="2"><%= t 'community.name'%></option>
    <option value="3"><%= t 'topic.name'%></option>
  </select>
  <%= submit_tag t("search"), :name => nil %>
<% end %>

app/views/layouts/_sidebar.html.erb
<section id="search_post">
  <%= render 'layouts/search_post' %>
</section>
  
<hr class="block"/>
  
<section id="links">
  <%= render 'layouts/links' %>
</section><br />
  
<section id="joined_communities">
  <%= render 'layouts/joined_communities'%>
</section>

<section id="helps">
	<%= link_to "About", about_path %> | <%= link_to "Help", basic_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DragonFly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=0.9, user-scalable=no" />
</head>
<body class="<%= @home_page ? 'homepage' : 'nothome'%>">
<% if user_signed_in? %>
  <nav id="navbar">
    <%= render 'layouts/navbar' %>
  </nav>
  
  <nav id="sidebar">
    <%= render 'layouts/sidebar' %>
  </nav>
<% end %>

<section id="content">
  <%= yield %>
</section>
<%= render 'layouts/analytics'%>
</body>
</html>